### ISSUE TITLE
What's wrong with "Illegal rate phy errors    9905850"

### ISSUE THREAD

**Issue by gmzhuo** [kvalo/ath11k-firmware#1]
Hi,
I'm try to running it on IPQ8071A, I can't received any packet.
When I cat /sys/kernel/debug/ath11k/ipq8074/mac0/fw_stats/pdev_stats,
It shows  "Illegal rate phy errors    9905850"

When will the firmware will report so many "Illegal rate phy errors    9905850"?
And no packet received. 
Is there any wrong with configuration?

Thanks!

**Comment by kvalo** [comment]
Please file bugs to bugzilla:

https://wireless.wiki.kernel.org/en/users/drivers/ath11k/bugreport
