### ISSUE TITLE
missing firmware for WCN6855/hw2.1

### ISSUE THREAD

**Issue by vicamo** [kvalo/ath11k-firmware#12]
As indicated in https://github.com/torvalds/linux/commit/d1147a316b53df9cb0152e415ec41dcb6ea62c1c ("ath11k: add support for WCN6855 hw2.1"), fw blob under `WCN6855/hw2.1` is required, but yet there is none available in the public.

**Comment by kvalo** [comment]
At the moment hw2.0 and hw2.1 share the firmware files, so just a simple symlink from hw2.1 to hw2.0 is enough. I added that now.
