### ISSUE TITLE
Ath11k firmware with incorrect regdb

### ISSUE THREAD

**Issue by dchard** [kvalo/ath11k-firmware#8]
Dear @kvalo 

During the porting of IPQ8074 platform to Openwrt, we noticed that the Ath11k firmware files (hosted in this repo) has incorrect regdb in it.

We tested:

IPQ8074 hw2.0: 2.4.0.1: add WLAN.HK.2.4.0.1-01746-QCAHKSWPL_SILICONZ-1 
and
IPQ8074 hw2.0: testing/2.5.0.1.r2: add WLAN.HK.2.5.0.1.r2-00013-QCAHKSWPL_SILICONZ-2

For example take a look at Hungary:

```
root@XAX6:~# iw reg get
global
country HU: DFS-ETSI
        (2400 - 2483 @ 40), (N/A, 20), (N/A)
        (5150 - 5250 @ 80), (N/A, 23), (N/A), NO-OUTDOOR, AUTO-BW
        (5250 - 5350 @ 80), (N/A, 20), (0 ms), NO-OUTDOOR, DFS, AUTO-BW
        (5470 - 5725 @ 160), (N/A, 26), (0 ms), DFS
        (5725 - 5875 @ 80), (N/A, 13), (N/A)
        (57000 - 66000 @ 2160), (N/A, 40), (N/A)

phy#1 (self-managed)
country HU: DFS-ETSI
        (2402 - 2472 @ 40), (N/A, 30), (N/A)
        (5170 - 5250 @ 80), (N/A, 30), (N/A), AUTO-BW
        (5250 - 5330 @ 80), (N/A, 24), (0 ms), DFS, AUTO-BW
        (5490 - 5590 @ 80), (N/A, 24), (0 ms), DFS, AUTO-BW
        (5590 - 5650 @ 40), (N/A, 24), (600000 ms), DFS, AUTO-BW
        (5650 - 5710 @ 40), (N/A, 24), (0 ms), DFS, AUTO-BW

phy#0 (self-managed)
country HU: DFS-ETSI
        (2402 - 2472 @ 40), (N/A, 30), (N/A)
        (5170 - 5250 @ 80), (N/A, 30), (N/A), AUTO-BW
        (5250 - 5330 @ 80), (N/A, 24), (0 ms), DFS, AUTO-BW
        (5490 - 5590 @ 80), (N/A, 24), (0 ms), DFS, AUTO-BW
        (5590 - 5650 @ 40), (N/A, 24), (600000 ms), DFS, AUTO-BW
        (5650 - 5710 @ 40), (N/A, 24), (0 ms), DFS, AUTO-BW
```

On 2.4GHz channel 12 and 13 are allowed in Hungary, yet it is not possible to set it even when the correct country code (HU in this case) is set.
On 5GHz the DFS time is set to 600 seconds, instead of 60 seconds.

A few ETSI countries were checked, and it seems all of them are affected.

As we know, the regdb is encoded with the firmware, so there is no other way to fix it on our side.

Would you please look into this?

Thanks!

**Comment by xsokolikx** [comment]
Hi,

I have the same problems with another selected country code (ES). Any news about this issue?

Tested with: 

- IPQ6018 hw1.0/2.4.0.1  WLAN.HK.2.4.0.1-01746-QCAHKSWPL_SILICONZ-1
- IPQ6018 hw1.0/2.5.0.1  WLAN.HK.2.5.0.1.r2-00013-QCAHKSWPL_SILICONZ-2

Thanks!

**Comment by dchard** [comment]
No updates yet, waiting for @kvalo to respond.

**Comment by robimarko** [comment]
@jmalinen Can you provide some info?
ETSI countries are really out of date and not aligned with the wireless-regdb at all.

**Comment by dchard** [comment]
Retested with newer firmware "WLAN.HK.2.5.0.1-01100-QCAHKSWPL_SILICONZ-1" again, same issues as in my first post. @robimarko is right: ETSI countries are still grossly out of date.
@kvalo @jmalinen would be nice to get some response, as this issue seemingly affect a lot of people.

**Comment by constantinosv** [comment]
Any updates on this? I am trying to setup WiFi AP for GB (United Kingdom) and the QCN9074 firmware gives different regulations than CRDA.

global
country GB: DFS-ETSI
	(2400 - 2483 @ 40), (N/A, 20), (N/A)
	(5150 - 5250 @ 80), (N/A, 23), (N/A), NO-OUTDOOR, AUTO-BW
	(5250 - 5350 @ 80), (N/A, 20), (0 ms), NO-OUTDOOR, DFS, AUTO-BW
	(5470 - 5730 @ 160), (N/A, 26), (0 ms), DFS
	(5725 - 5850 @ 80), (N/A, 23), (N/A), NO-OUTDOOR
	(57000 - 71000 @ 2160), (N/A, 40), (N/A)

phy#0 (self-managed)
country GB: DFS-ETSI
	(2402 - 2472 @ 40), (N/A, 20), (N/A)
	(5170 - 5250 @ 80), (N/A, 23), (N/A), NO-OUTDOOR, AUTO-BW
	(5250 - 5330 @ 80), (N/A, 23), (0 ms), NO-OUTDOOR, DFS, AUTO-BW
	(5490 - 5590 @ 80), (N/A, 24), (0 ms), DFS, AUTO-BW
	(5590 - 5650 @ 40), (N/A, 24), (600000 ms), DFS, AUTO-BW
	(5650 - 5710 @ 40), (N/A, 24), (0 ms), DFS, AUTO-BW

**Comment by dchard** [comment]
Well, the main issue is two-fold:

1. A part of it is resolved via this patch: [https://git.kernel.org/pub/scm/linux/kernel/git/kvalo/ath.git/commit/?id=086c921a354089f209318501038d43c98d3f409f](url)

2. The other issue is that the vendors are supplying so called board data files (BDFs) with their devices which are grossly out of date, and ath11k (for most but not all devices) are using the reg domain data coming in the BDFs, rather than the official linux regdb. This is still true, although it is not a bug.

So I am closing this one.
